from textual.theme import Theme

THEMES: dict[str, Theme] = {
    "tokyonight": Theme(
        name="tokyonight",
        primary="#7aa2f7",
        secondary="#9d7cd8",
        accent="#7dcfff",
        foreground="#c0caf5",
        background="#1a1b26",
        success="#9ece6a",
        warning="#e0af68",
        error="#db4b4b",
        surface="#24283b",
        panel="#414868",
        dark=True,
    ),
    "tokyonight-storm": Theme(
        name="tokyonight-storm",
        primary="#7aa2f7",
        secondary="#9d7cd8",
        accent="#7dcfff",
        foreground="#c0caf5",
        background="#24283b",
        success="#9ece6a",
        warning="#e0af68",
        error="#db4b4b",
        surface="#1f2335",
        panel="#414868",
        dark=True,
    ),
    "tokyonight-light": Theme(
        name="tokyonight-light",
        primary="#2e7de9",
        secondary="#7847bd",
        accent="#007197",
        foreground="#3760bf",
        background="#e1e2e7",
        success="#587539",
        warning="#8c6c3e",
        error="#c64343",
        surface="#d0d5e3",
        panel="#c4c8da",
        dark=False,
    ),
    "catppuccin-mocha": Theme(
        name="catppuccin-mocha",
        primary="#89b4fa",
        secondary="#cba6f7",
        accent="#94e2d5",
        foreground="#cdd6f4",
        background="#1e1e2e",
        success="#a6e3a1",
        warning="#f9e2af",
        error="#f38ba8",
        surface="#313244",
        panel="#45475a",
        dark=True,
    ),
    "gruvbox": Theme(
        name="gruvbox",
        primary="#83a598",
        secondary="#d3869b",
        accent="#8ec07c",
        foreground="#ebdbb2",
        background="#282828",
        success="#b8bb26",
        warning="#fabd2f",
        error="#fb4934",
        surface="#3c3836",
        panel="#504945",
        dark=True,
    ),
    "nord": Theme(
        name="nord",
        primary="#88c0d0",
        secondary="#81a1c1",
        accent="#8fbcbb",
        foreground="#d8dee9",
        background="#2e3440",
        success="#a3be8c",
        warning="#ebcb8b",
        error="#bf616a",
        surface="#3b4252",
        panel="#434c5e",
        dark=True,
    ),
    "onedark-pro": Theme(
        name="onedark-pro",
        primary="#61afef",
        secondary="#c678dd",
        accent="#56b6c2",
        foreground="#abb2bf",
        background="#282c34",
        success="#98c379",
        warning="#d19a66",
        error="#e06c75",
        surface="#21252b",
        panel="#2c313c",
        dark=True,
    ),
}

DEFAULT_THEME = "tokyonight"
